const pets = [
  {
    id: 1,
    name: "Rottweiler",
    location: "Ameerpet, Hyderabad",
    isReserved: true,
    price: "₹ 15,000/-",
    postDate: "22/04/2025",
    image: "https://petlisting-internship-1.onrender.com/images/rottweiler.jpg",
    age: "2 Yrs 8 Months",
    gender: "Female",
    color: "Tri Color",
    size: "Medium",
    owner: {
      name: "Ranjith Soma",
      location: "Ameerpet, Hyderabad",
      phoneVerified: true,
      emailVerified: true,
    },
    vaccinated: true,
  transport: true,
    about: [
      "The Rottweiler Dog, also lovingly called Alsatians by the British, is a loyal, versatile and intelligent dog breed. They are originally from Germany and are called 'DEUTSCHER SCHÄFERHUND' in German.",

"They are bred for sheep herding and to protect them from wolves. They are known to have high stamina and are used in military, police forces, in search and rescue operations or even as service dogs.",

"They are excellent guard dogs and are equally patient with children and people of all ages. Early socialization helps them thrive in all kinds of families.",

"They are excellent guard dogs and are equally patient with children and people of all ages. Early socialization helps them thrive in all kinds of families. They are excellent guard dogs and are equally patient with children.",

"They became very famous in the United States in the early 1900s and are considered the ideal breed for the K9 dog squad. READ MORE",
    ],
  },
  {
    id: 2,
    name: "Labrador",
    location: "Madhapur, Hyderabad",
    isReserved: false,
    price: "₹ 12,000/-",
    postDate: "01/09/2025",
    image: "https://petlisting-internship-1.onrender.com/images/labrador.jpg",
    age: "1 Yr 3 Months",
    gender: "Male",
    color: "Golden",
    size: "Large",
    owner: {
      name: "Suresh Kumar",
      location: "Madhapur, Hyderabad",
      phoneVerified: false,
      emailVerified: true,
    },
      vaccinated: true,
  transport: true,
    about: [
      "The Labrador Retriever is one of the most popular dog breeds in the world.",
      "They were originally bred for retrieving fishing nets and game.",
      "Labradors are playful, loyal, and thrive in active households.",
    ],
  },
  {
    id: 3,
    name: "German Shepherd",
    location: "Kukatpally, Hyderabad",
    isReserved: false,
    price: "₹ 18,000/-",
    postDate: "15/08/2025",
    image: "https://petlisting-internship-1.onrender.com/images/germanshepherd.jpg",
    age: "3 Yrs",
    gender: "Male",
    color: "Black & Tan",
    size: "Large",
    owner: {
      name: "Anil Reddy",
      location: "Kukatpally, Hyderabad",
      phoneVerified: true,
      emailVerified: false,
    },
      vaccinated: true,
  transport: true,
    about: [
      "The German Shepherd is a courageous and highly intelligent breed.",
      "They are commonly used in police, military, and search-and-rescue missions.",
      "They are protective yet affectionate, making them excellent family dogs.",
    ],
  },
  {
    id: 4,
    name: "Beagle",
    location: "Gachibowli, Hyderabad",
    isReserved: true,
    price: "₹ 10,000/-",
    postDate: "10/07/2025",
    image: "https://petlisting-internship-1.onrender.com/images/beagle.jpg",
    age: "2 Yrs",
    gender: "Female",
    color: "White & Brown",
    size: "Small",
    owner: {
      name: "Priya Sharma",
      location: "Gachibowli, Hyderabad",
      phoneVerified: true,
      emailVerified: true,
    },
      vaccinated: true,
  transport: true,
    about: [
      "The Beagle is a small hound breed with an excellent sense of smell.",
      "They are friendly, curious, and great with children.",
      "Beagles are active and require regular exercise and playtime.",
    ],
  },
  {
    id: 5,
    name: "Pomeranian",
    location: "Secunderabad, Hyderabad",
    isReserved: false,
    price: "₹ 8,000/-",
    postDate: "25/06/2025",
    image: "https://petlisting-internship-1.onrender.com/images/pomeranian.jpg",
    age: "1 Yr 6 Months",
    gender: "Male",
    color: "White",
    size: "Small",
    owner: {
      name: "Kiran Kumar",
      location: "Secunderabad, Hyderabad",
      phoneVerified: false,
      emailVerified: true,
    },
      vaccinated: true,
  transport: true,
    about: [
      "The Pomeranian is a small, fluffy companion dog full of energy.",
      "They are very intelligent, playful, and affectionate.",
      "Despite their small size, they are confident and alert watchdogs.",
    ],
  },
];

module.exports = pets;
